# Generated by Django 5.1.3 on 2024-12-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
