# Generated by Django 5.1.3 on 2024-12-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_servicetype_clinic_closing_time_clinic_opening_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='icon',
            field=models.ImageField(default='', upload_to='icons/'),
            preserve_default=False,
        ),
    ]
