# Generated by Django 5.1.3 on 2024-12-19 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_servicetype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicimage',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.clinic'),
        ),
    ]
