# Generated by Django 5.1.3 on 2024-12-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_clinicimage_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
