# Generated by Django 5.1.3 on 2025-01-04 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_clinic_latitude_alter_clinic_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='managers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
