# Generated by Django 5.1.3 on 2025-01-04 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_clinic_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='managers',
            field=models.ManyToManyField(related_name='clinics', to=settings.AUTH_USER_MODEL),
        ),
    ]
